- Komshanov_Alexander/assignments/assignment1/KNN.ipynb
- Komshanov_Alexander/assignments/assignment1/knn.py
- Komshanov_Alexander/assignments/assignment1/metrics.py
Реализовал KNN для решения задачи классификации.
Подобрал гиперпараметр k методом кросс-валидации.
На бинарном классификаторе `f1 > 0.7`
На мультиклассовом `accuracy = 0.21`
Комшанов Александр
> Задание 1.1

- Rebrik_Dmitry/assignments/assignment1/Linear classifier.ipynb
- Rebrik_Dmitry/assignments/assignment1/gradient_check.py
- Rebrik_Dmitry/assignments/assignment1/linear_classifer.py
Реализовал линейный классификатор и добился точности 0.202
> assigment 1.2 done

- Julia_Sergeeva/assignment1/KNN.ipynb
- Julia_Sergeeva/assignment1/knn.py
- Julia_Sergeeva/assignment1/metrics.py
В финальном тесте точность составила 0.21, лучшие k для бинарной классификации k=2, для многоклассовой: k=1.
> Task 1.1 completed

- Task1/pchizhov/KNN.ipynb
- Task1/pchizhov/knn.py
- Task1/pchizhov/metrics.py
В задании 1.1 реализован KNN-классификатор (метод ближайших соседей) с бинарной и многоклассовой классификацией, оценкой результата по метрикам и выбором наилучшего гиперпараметра k на основе кросс-валидации.
В бинарной классификации усредненный f1 score составил 0.7. В многоклассовой классификации усредненная точность составила 0.23.
> Task 1.1 done

- Task1/izukovdariy/KNN.ipynb
- Task1/izukovdariy/knn.py
- Task1/izukovdariy/metrics.py
> 1.1 izukova d

- Task1/a-koshmarov/.ipynb_checkpoints/Linear classifier-checkpoint.ipynb
- Task1/a-koshmarov/gradient_check.py
- Task1/a-koshmarov/linear_classifer.py
- Task2/a-koshmarov/Neural Network.ipynb
- Task2/a-koshmarov/gradient_check.py
- Task2/a-koshmarov/layers.py
- Task2/a-koshmarov/metrics.py
- Task2/a-koshmarov/model.py
- Task2/a-koshmarov/optim.py
- Task2/a-koshmarov/trainer.py
Задание 1.2
Реализовал линейный классификатор.
На проверочных данных `accuracy = 0.228` с гиперпараметрами `lr = 0.001`, `reg = 1e-05`
На тестовых данных `accuracy = 0.195`
Задание 2.1
Реализовал простую NN
На проверочных данных `accuracy = 0.73`
На тестовых данных `accuracy = 0.69`
Комшанов Александр
> Задание 1.2 & 2.1

- Task2/dimonker/.gitignore
- Task2/dimonker/Neural Network.ipynb
- Task2/dimonker/gradient_check.py
- Task2/dimonker/layers.py
- Task2/dimonker/metrics.py
- Task2/dimonker/model.py
- Task2/dimonker/optim.py
- Task2/dimonker/trainer.py
> task 2.1  done

- Task2/JustEvgeniy/.gitignore
- Task2/JustEvgeniy/Neural Network.ipynb
- Task2/JustEvgeniy/download_data.sh
- Task2/JustEvgeniy/gradient_check.py
- Task2/JustEvgeniy/layers.py
- Task2/JustEvgeniy/metrics.py
- Task2/JustEvgeniy/model.py
- Task2/JustEvgeniy/optim.py
- Task2/JustEvgeniy/requirements.txt
- Task2/JustEvgeniy/trainer.py
Разобрана и реализована нейросеть с одним скрытым слоем. Изучен алгоритм обратного распространения ошибки, улучшенные методы градиентного спуска.
Перебором гиперпараметров была найдена модель с самой высокой точностью на validation датасете:
`best validation accuracy achieved: 0.788`
Точность на тестовом датасете:
`Neural net test set accuracy: 0.76`
> Assignment 2.1 Evgeniy Vasilyev 

- Task2/coffecom/Neural_Network.ipynb
- Task2/coffecom/gradient_check.py
- Task2/coffecom/layers.py
- Task2/coffecom/metrics.py
- Task2/coffecom/model.py
- Task2/coffecom/optim.py
- Task2/coffecom/trainer.py
Лучшая точность на тренировочной выборке 0,89 с параметрами: learning_rate = 0.1, learning_rate_decay = 0.8, num_epochs=40, batch_size=64, reg_strength = 1e-06, hidden_layer_size = 128 с этими параметрами на тесте получилась точность 0,744
> Task 2.1 complete

- Task2/dimonker/.gitignore
- Task2/dimonker/Neural Network.ipynb
- Task2/dimonker/PyTorch.ipynb
- Task2/dimonker/gradient_check.py
- Task2/dimonker/layers.py
- Task2/dimonker/metrics.py
- Task2/dimonker/model.py
- Task2/dimonker/optim.py
- Task2/dimonker/trainer.py
> Task 2.2 done 

- Task2/SkymeFactor/Neural Network.ipynb
- Task2/SkymeFactor/PyTorch.ipynb
- Task2/SkymeFactor/gradient_check.py
- Task2/SkymeFactor/layers.py
- Task2/SkymeFactor/metrics.py
- Task2/SkymeFactor/model.py
- Task2/SkymeFactor/optim.py
- Task2/SkymeFactor/trainer.py
Везь день дебажил, оказалось, датасет не загрузил xD Accuracy ~0.65, двухслойная нейронная сеть
> Task 2 complete (full)

- Task1/pchizhov/Linear classifier.ipynb
- Task1/pchizhov/linear_classifer.py
В ходе задания был реализован линейный классификатор для задачи многоклассовой классификации с использованием функции softmax и l2-регуляризации. 
Лучшая точность на валидационных данных составила 0.247
Точность на тестовых данных составила 0.209
> Task 1.2 done

- Task3/egoarka/CNN.ipynb
- Task3/egoarka/PyTorch_CNN.ipynb
- Task3/egoarka/gradient_check.py
- Task3/egoarka/layers.py
- Task3/egoarka/model.py
- Task3/egoarka/optim.py
- Task3/egoarka/requirements.txt
- Task3/egoarka/trainer.py
I've completed Assignment 3 (task 3.1 and 3.2).
Final test accuracy -  0.96
> Task 3.1 & 3.2

- Task2/kinoooshnik/PyTorch.ipynb
Создал трехслойную нейросеть для задачи классификации картинок по классам 0-9 с использованием фреймворка PyTorch. Точность на тестовой выборке составила 0.8483.
> Task 2.2 Semiletov Alexander

- Task2/coffecom/PyTorch.ipynb
Задание 2,2, в итоговой модели добавила ещё один скрытый слой, заменила ReLU на LeakyReLu и использовала Adam вместо SGD, после обучения на 7 эпохах точность на тесте 0.8442
> Task 2.2 test accuracy 0.8442

- Task2/JustEvgeniy/PyTorch.ipynb
Разобрался в библиотеке PyTorch. Реализовал нейросеть для классификации номеров домов.
Итоговая точность на тестовых данных: 0.8568
> Assignment 2.2 Evgeniy Vasilyev 

- Task3/chinarev/CNN.ipynb
- Task3/chinarev/gradient_check.py
- Task3/chinarev/layers.py
- Task3/chinarev/metrics.py
- Task3/chinarev/model.py
- Task3/chinarev/optim.py
- Task3/chinarev/trainer.py
Task 3.1 done (ONLY FIRST PART)
Точность 0.23 +- 0.01
> Task 3.1 done

- Task3/SkymeFactor/CNN.ipynb
- Task3/SkymeFactor/PyTorch_CNN.ipynb
- Task3/SkymeFactor/gradient_check.py
- Task3/SkymeFactor/layers.py
- Task3/SkymeFactor/metrics.py
- Task3/SkymeFactor/model.py
- Task3/SkymeFactor/optim.py
В 3.1 не совсем до конца заоверфитилась, получилось 0,9982.
В 3.2 применил модель похожую на VGG-16 с учётом размера входных данных и набрал 84,7% с оптимизатором Adam. Как оказалось, 1050Ti довольно плохо справляется с такими задачами, один прогон на 20 эпох у меня занимал почти 15 минут. И ещё одно наблюдение, в ноутбуках не очищается использованная память GPU, поскольку объекты всё ещё хранятся в кэше ноутбука, задание стоило назвать "сам себе garbage-collector"
> Task 3 done

- Task2/izukovdariy/Neural Network.ipynb
- Task2/izukovdariy/PyTorch.ipynb
- Task2/izukovdariy/gradient_check.py
- Task2/izukovdariy/layers.py
- Task2/izukovdariy/metrics.py
- Task2/izukovdariy/model.py
- Task2/izukovdariy/optim.py
- Task2/izukovdariy/trainer.py
Использовала несколько линейный классификаторов вместе, изучен новый метод градиентного спуска Momentum SGD
best validation accuracy achieved: 0.888000
Neural net test set accuracy: 0.725000
> Task 2 full

- Task2/kmosunoff/PyTorch.ipynb
Поработал с основными инструментами библиотеки PyTorch для создания нейронных сетей, используя линейные/нелинейные слои, нормализацию батчей, понижение темпа обучения, стохастический градиентный спуск и Adam. Была построена матрица неточностей. Показатели на последнем этапе:
learning_rate = 9.317816802545169e-05
weight_decay = 0.10712127522997833
batch_size = 236
best_val_accuracy = 0.8107978977544195
Test accuracy: 0.7866
> Task 2.2 PyTorch basics

- Task2/Lexanus686/PyTorch.ipynb
@toshiks 
В задании 2.2 я поработал с фреймворком PyTorch, разобрался с тем, как строятся нейронные сети, натренировал несколько больших моделей
Точность на тестовой выборке: 0.7709
> Task 2.2 Done
